version: '3'
services:
  nginx-rtmp:
    container_name: nginx-rtmp
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
    volumes:
      - ./recordings:/recordings
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Taipei
